# Generated by Django 3.1.4 on 2020-12-17 05:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalculateResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_num', models.IntegerField()),
                ('date_result', models.DateTimeField(default=django.utils.timezone.now)),
                ('username', models.CharField(max_length=30)),
                ('input_a', models.IntegerField()),
                ('input_b', models.IntegerField()),
                ('input_c', models.IntegerField()),
            ],
        ),
    ]
