# Generated by Django 3.1.4 on 2020-12-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculateresults',
            name='input_a',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='calculateresults',
            name='input_b',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='calculateresults',
            name='input_c',
            field=models.CharField(max_length=30),
        ),
    ]
